---
- block:
  - name: Get keybase
    get_url:
      url: 'https://dist.keybase.io/linux/deb/keybase-latest-amd64.deb'
      dest: '{{ home_dir }}/keybase-latest-amd64.deb'

  - name: Install keybase
    apt:
      deb: '{{ home_dir }}/keybase-latest-amd64.deb'

  when: ansible_os_family == "Debian"

- block:
  - name: Get keybase Arch
    pacman:
      name: keybase
      state: present
  when: ansible_os_family == "Archlinux"
