- include_vars: "{{ ansible_os_family }}.yml"

- include: debian_dependencies.yml
  when: ansible_os_family == "Debian"
- include: arch_dependencies.yml
  when: ansible_os_family == "Archlinux"
- include: keybase.yml  
- include: go.yml
- include: zsh.yml
- include: screen.yml
- include: vim.yml
- include: tmux.yml
